services:
  web:
    command: python manage.py runserver 0.0.0.0:8000 --settings=project.settings.development
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=project.settings.development
